import type { Metadata } from "next";
import { Header } from '@/components/shared/Header'
import { Footer } from '@/components/shared/Footer'
import { SocialCTA } from '@/components/shared/SocialCTA'
import 'bootstrap/dist/css/bootstrap.min.css';

import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="preload" href="/images/la-negra-hero.webp" as="image" />
      <body
        
      >
        <main className="flex flex-col min-h-screen bg-transparent">
          <Header /> 
          <SocialCTA />                           
          { children }
          <Footer />
        </main>
      </body>
    </html>
  );
}
